sudo: required
services:
  - docker

  before_install:
    - docker build -t pradeepsync04/docker-react -f Dockerfile.dev .

script:
  - docker run pradeepsync04/docker-react npm run test -- --coverage